### ISSUE TITLE
Forklare hvorfor GPS_RX er koblet til TX på GPS-en (+ støvsensor)

### ISSUE THREAD

**Issue by fjukstad** [fjukstad/luft#15]
Hei,

Kan vi få inn en liten setning som forklarer hvorfor `GPS_RX = 7`, når `RX` på GPS-en er koblet til pinne 6? Elevene på en av skolene syns dette var litt rart at pinout-figuren ikke stemte overens med koden. Samme gjelder for støvsensoren.

Takk! 

Bjørn

**Comment by couven92** [comment]
Fixed in #19
