### ISSUE TITLE
Filename on upload privacy concerns

### ISSUE THREAD

**Issue by couven92** [fjukstad/luft#26]
When uploading a student file, the Browser will send the entire filename to the data storage backend.

Eg.: `C:\Users\Fredrik\Documents\airbit\datalog.csv`

This means that the file on the data-backend can be attributed to a single person `Fredrik`, meaning that the data is no longer anonymised.

It should be checked that this still is in compliance with privacy legislation.

For reference a quote form the (Norwegian) form that has been issued to the students and their parents:

> Måledataene som elevene samler inn (gruppevis på tre og tre elever) vil bli lagt åpent ut på web på http://airbit.uit.no/, men vil ikke bli linket til den enkelte elev eller gruppe. Det vil ikke være mulig å si hvilke måledata som er samlet inn av hvilke grupper.

Strictly speaking transmitting a filename which may contain a user's personal name or login alias might be seen as a vioaltion to this statement.

*Suggestion for fix:* Re-introduce UUID (or similar) filenaming strategy on upload to generate a randomized filename. While this in some cases might make debugging harder, it would ensure proper anonymisation of the uploaded data. Debugging would have to be done with timestamps alone.

**Comment by fjukstad** [comment]
We'll throw away the path and keep the filename. @ninaangelvik is on it.

**Comment by couven92** [comment]
Closed in https://github.com/fjukstad/luft/pull/31
