### ISSUE TITLE
Funky graphs

### ISSUE THREAD

**Issue by fjukstad** [fjukstad/luft#34]
(First reported by Anders in Bodø)

There are some funky stuff going on in the plotting on the air:bit page. I suspect that the strange lines we're seeing (see screenshot) is because the visualization is plotting the data from all sensors sequentially. For example if we're looking at data from two kits, it will first plot all measurements from the first kit, and then all the data from second kit. The strange lines are lines between the last measurement from one kit, and the first measurement from the next kit.

![screen shot 2018-02-12 at 11 18 56](https://user-images.githubusercontent.com/1394111/36092133-9844dc16-0fe6-11e8-8d1f-c2f300cc28e3.png)

Who wants to fix? 

Cheers!

**Comment by ninaangelvik** [comment]
I have grouped the records by timestamp as a quick fix. I will try changing the plotting library, to see if it can provide us with a better solution.

**Comment by fjukstad** [comment]
Fixed in 2317650ec27c12d2db4b5d1a0e1ad6fad669c537.
