### ISSUE TITLE
Student data and NILU graphs overlap

### ISSUE THREAD

**Issue by couven92** [fjukstad/luft#39]
On the `historikk` page, when selecting both student data and NILU data, the graphs go over their boundaries, the result is not pretty:

![image](https://user-images.githubusercontent.com/8759693/36527521-5cddc768-17b2-11e8-9c40-2c6963f7f789.png)

In the picture above, you can see that the NILU heading is partly obscured by the graph above it.

**Comment by couven92** [comment]
The same applies for the bottom of the NILU graphs, they overlop the `<hr/>` line that separates the main page content from the footer.

**Comment by fjukstad** [comment]
Great. Could you have a look at it @couven92 ?

**Comment by ninaangelvik** [comment]
Fixed it.
