### ISSUE TITLE
Files

### ISSUE THREAD

**Issue by fjukstad** [fjukstad/luft#49]
Hi,

Can we remove the different `.sh` and `.cmd` files from the root of the repo? Or move them elsewhere? Also, do we need the `.vscode`-stuff? 

Thanks,
Bjørn

**Comment by couven92** [comment]
@fjukstad Sorry, these files were never meant to be there in the first place, I added their commit by mistake. Gone now.

**Comment by fjukstad** [comment]
No worries, thanks!
